### ISSUE TITLE
Port to Python or R language?

### ISSUE THREAD

**Issue by brylie** [JonathanAMichaels/hebbRNN#2]
Thanks for this great work, and very interesting library. What are your thoughts on the possibility of porting the code to Python or R-Language?

**Comment by JonathanAMichaels** [comment]
Thanks. A port is very possible, especially to Python, but I will not be making any ports to these languages myself. However, a more specific implementation of this training method has been coded in Python by the author mentioned in the Acknowledgements section (Thomas Miconi), and he may be willing to share that if you contact him.

**Comment by JonathanAMichaels** [comment]
I just realized that original implementation was in C++, not Python. Sorry for the error!
